Name: Deploy
Actions:
  - Name: Deploy
    ActionTypeId:
      Category: Deploy
      Owner: AWS
      Provider: CodeDeploy
      Version: '1'
    RunOrder: 1
    Configuration:
      ApplicationName: DeployToECS
      DeploymentGroupName: Deploy-to-ECS
      TaskDefinition: arn:aws:ecs:ap-south-1:891365734547:task-definition/vprofileapptask:1
      ContainerName: vproapp
      ContainerPort: 8080
    OutputArtifacts: []
    InputArtifacts:
      - Name: BuildArtifact
    Region: ap-south-1
    Namespace: DeployVariables
